### PR TITLE
UploadedFile->guessExtenstion() & Config/Mimes::guessExtensionFromType() improvements.

### PR DESCRIPTION
**Pull request by nowackipawel**
#1367 
guessExtension() more predictable

### CODE REVIEW

**Comment by lonnieezell** [comment]
The point of that method is to guess the file type without any user-supplied input and your variation uses the client-supplied file extension which is a potential security issue. With your version someone could pass a potentially harmful file but give it an extension that appeared harmless. If the app was poorly programmed it could potentially be something that gets executed, or be javascript that gets displayed in someone's browser when they thought it was an image, etc.

**Comment by lonnieezell** [comment]
I'm sorry. I read the logic wrong the other night. What you're doing there actually does work and still keeps things safe. Sorry about that. Will merge.

**Comment by nowackipawel** [comment]
thx.

**Comment by daljit3** [comment]
Hi - there is an issue with the new update or maybe due to changes by someone else.

**in Config/Mimes.php** this method below returns null.
```
public static function guessExtensionFromType(string $type, ?string $proposed_extension = null) {
return null;
}
```
in **System/HTTP/Files/UploadedFile.php** return type must be string - so the null return from the above throws a critical error.
```
public function guessExtension(): string 
{
		return \Config\Mimes::guessExtensionFromType($this->getMimeType(), $this->getClientExtension());
}

```

**Comment by daljit3** [comment]
Shall I report it as a bug ?

**Comment by nowackipawel** [comment]
Will fix it asap - tmrw

**Comment by nowackipawel** [comment]
My defs of this method was exact the same as was in File . However type hinting should be ?string as is in Config\Mimes. Pr#1399

**Pull request merged**
