### PR TITLE
Style guide: Address control structures & alignment.

### PR DESCRIPTION
**Pull request by jim-parry**
- Naming: being equally picky about interface & trait names.
- Address control structures, with suggestion(s) from url_helper PR.  Note: the strictly braced blocks seem to fit better into the current guidelines, though at the expense of extra lines.
- Propose more flexible tab & space treatment, for indenting & alignment. Trying to come up with something that *everyone* can live with. We spend way too much time fighting this, arguing over its interpretation, or fighting our IDEs to format things the way we think the guidelines are to be interpreted.

### CODE REVIEW

**Comment by jim-parry** [comment]
I am surprised that this PR hasn't triggered a flood of responses, specifically to my proposal for alignment/indenting!

My reasoning: readability is good (we all agree), a style guide is good (for consistency, we all agree), and workable rules for these are good (but we differ on what they should be).
The problem I see: the indenting/alignment rules we have present a barrier to participation by the community.

This PR relaxes the alignment/indenting rules, allowing either tabs or spaces for readibility, but insisting on a tab spacing of 4 if that approach is used. 

Down the road, an automated tool should be able to automatically reformat to our liking. If it can't, that doesn't speak well to the reasonability of our style guide. In the meantime, we get to get on with contributing!

This PR doesn't bring us any closer to or further from PSR2 compliance, which is fine with me :-/

**Comment by lonnieezell** [comment]
I like it. Push it :)

**Comment by jim-parry** [comment]
What do you think of the control structures? Strictly braced, or allow the "short form"?

**Comment by InsiteFX** [comment]
Short form will cause problems later on down the road.

**Comment by lonnieezell** [comment]
@InsiteFX may be right, unfortunately. If we change it, though, we'll have to check back through the code. I'm pretty sure I used it in a few places.

**Comment by mwhitneysdsu** [comment]
In my opinion, if the short form is permitted at all, it should only be permitted for one-line statements. In other words, with no `else` or `elseif`. The extra vertical space used by the braces is one of my complaints regarding the Allman style, but vertical space is not the only consideration when writing code, and the only benefit of the short form that comes to mind is to save vertical space.

My biggest issue with the mixed indentation rules comes down the road, when someone edits an existing file and uses an indentation that isn't the same as the rest of the file. Either the file ends up with mixed indentation, or the editor/IDE converts the indentation (or can we just convert it through Travis or some other method?).

**Comment by jim-parry** [comment]
1) It sounds like brace-bracketed bodies for control structures are the way to go. 

2) Yes, this will mean some non-conforming code at the moment, but those instances will get sorted out over time, and/or by a tool used in Travis. 

2b) I am going to raise a help wanted issue (or three) leading to that, other than the Coding Style Checker issue 21 already there. I really hope that style issues can be automated, so we don't have to spend so much time addressing them!

**Pull request merged**
