### PR TITLE
Rework/encryption

### PR DESCRIPTION
**Pull request by jim-parry**
Simplified & completed Encryption manager & OpenSSLHandler.
Optional HMAC & encoding added.
Unit testing 100%, fixing previously skipped tests.
Updated user guide accordingly.

### CODE REVIEW

**Comment by jim-parry** [comment]
Unit testing fix & encryption parameter simplification coming later today.

**Comment by jim-parry** [comment]
Hmmm ... "hash_hkdf" is not part of the core until PHP 7.1.2, hence the travis-CI failures with PHP7.0.

@lonnieezell  Would you like to see a fallback implementation for hash_hkdf, or is it better to increase the PHP version needed for CI4?

**Comment by lonnieezell** [comment]
Requiring 7.1 seems to be pushing it as far as host support I would think, though I haven't seen any numbers recently to be honest. Is that crucial to be able to use the Encryption library at all, or can we say the rest works fine with 7.0, but 7.1 is needed for that feature?

**Comment by jim-parry** [comment]
Lifted the code from CI3, to use as a fallback - that appears to have fixed the problem :)

**Comment by lonnieezell** [comment]
@jim-parry that works :)

**Comment by narfbg** [comment]
Huh? Why is HMAC optional?

Also: key is always stored in object state, key is reused for encryptiong & HMAC, authentication isn't time-safe, randomness is not guaranteed ... probably more.
This reverts almost all progress made with `CI_Encryption` in CI3. Why did anything need changing?

**Comment by narfbg** [comment]
A port would preserve the same functionality; this is not a port, nor is it an acceptable cryptographic solution. All of the things I mentioned in my previous comment would be considered vulnerabilities.

>  Authentication - what would you suggest?

It being time-safe? See `hash_equals()`.

> Key reuse - are you suggesting that it be derived every time & not stored?

I didn't even know it was stored. What I meant is that the same key is used for encryption & authentication.  
Technically the HMAC key is derived from the encryption one, but that's practically the same thing - you shouldn't be able to recover one key from having the other, in either direction. This is where HKDF is useful ... see how CI3 uses it.

> Why change? PHP7 provides hkdf(), libsodium, not mcrypt.

This here doesn't use libsodium; CI3 defaults to OpenSSL instead of mcrypt, and uses HKDF for a specific purpose. This patch here uses HKDF just for the sake of using it.

Yes, some chances are due - dropping mcrypt support, maybe allowing only AES and perhaps switching to CTR mode - all of this amounts to just simplifying the CI3 code, but this is not what's happening.

>  I checked the other frameworks, and they generally provide AES-256 or else don't address encryption.

And that's fine. But what we have here is broken in too many ways.
It's better thrown away and either really port what CI3 has, or suggest/require defuse/php-encryption via Composer.

**Comment by jim-parry** [comment]
Agreed - "port" is the wrong word to use ... my bad :(
I have a separate PR adding the Sodium handler, and I incorporated random_bytes & hash_equals.
I still need to dive more into HMAC/HKDF.

The CI3 encryption feels overly flexible/complicated, compared to libsodium or defuse/php-encryption.  If this implementation won't serve well, then defuse's might be a better choice, as an addin.

**Comment by narfbg** [comment]
Yes, CI3's encryption did turn out too complicated. I'm all for simplifying it if it is to be included in CI4, but I have to reiterate that this isn't what's going on here.

Cryptography isn't trivial ... You can't just add, remove, copy-paste and move bits around. I learned the hard way that you need to know 100% what you are doing, and every little detail is important, design included.

I say just drop this and add sodium_compat and/or defuse/php-encryption, *without* wrappers, adapters, etc.

**Comment by jim-parry** [comment]
Hmmm - I am in favor of stripping options out of what I have done, resulting in a simple string encryption/decryption ability. Use AES-256-? and SHA512, forced HMAC ... similar to what is being done with Sodium. I am reluctant to add dependencies to the framework.
@lonnieezell What do you think?

**Comment by lonnieezell** [comment]
In this case, I have no qualms about a third-party lib, especially since it's built into 7.2. I'm not a security expert and I'd rather rely on those who know a lot more about it than me. I say go for it.

**Pull request merged**
