### PR TITLE
Filesystem_helper

### PR DESCRIPTION
**Pull request by Portaflex**
Initial pull request. Filesystem_helper merging directory_helper, file_helper and path_helper.

Don't have tests because can't get vfsStream to work.

### CODE REVIEW

**Comment by lonnieezell** [comment]
What issues are you having getting vfsStream to work? I've never actually used it but can maybe point you in the right general direction. I appreciate all of the help, but  we really need tests on all of these things...

**Comment by Portaflex** [comment]
I can install vfsStream using composer, but can't instantiate none of its files. Don't know how to manage namespaces and psr-4 in this case:

``
<?php

namespace CodeIgniter\Helpers;

class FilesystemHelperTest extends \CIUnitTestCase
{	
    public function setUp()
	{
		helper('filesystem');
		
		vfsStreamWrapper::register();
		vfsStreamWrapper::setRoot(new vfsStreamDirectory('testDir'));
		
		$this->_test_dir = vfsStreamWrapper::getRoot();
		
	}
     // ...
``

**Comment by lonnieezell** [comment]
Looking at the [example in the wiki](https://github.com/mikey179/vfsStream/wiki/Example), you're missing the namespace for vfsstream. Outside of the class (right below the namespace declaration) you'd need to put: 

```
use org\bovigo\vfs\vfsStream,
    org\bovigo\vfs\vfsStreamDirectory;
```

**Comment by lonnieezell** [comment]
@Portaflex are you going to be able to do any more on this?

**Comment by Portaflex** [comment]
I can't instantiate vfsStream. Sorry. So, that's a "no".

**Comment by lonnieezell** [comment]
Even with the `use` statement in place? Hmmm. Alright, I'll try to take a look at it soon.

**Pull request merged**
