### PR TITLE
add more test function to populateHeaders

### PR DESCRIPTION
**Pull request by BoyDiao**
Signed-off-by:Lin Yang <bcityang@gmail.com>

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please break these different checks into individual test methods. That makes it easier to maintain, test (using phpunit's --filter flag) and to see where things go wrong.

**Comment by BoyDiao** [comment]
image

**Comment by BoyDiao** [comment]
OK I will try to break it in parts and see what happend

**Comment by jim-parry** [comment]
"Do or do not. There is no try." ... from a certain Jedi Knight :-/

**Comment by jim-parry** [comment]
testPopulateHeadersKeyNotExisit() is misspelled ... should be testPopulateHeadersKeyNotExists() ... oops

**Comment by jim-parry** [comment]
Your commits should be GPG-signed.

**Comment by AntonyGarand** [comment]
Is there a reason you're using a new blank line under each line of code?

**Pull request merged**
