### PR TITLE
Merge pull request #1 from bcit-ci/develop

### PR DESCRIPTION
**Pull request by v-leonhou**
merge the remote branch

### CODE REVIEW

**Comment by v-leonhou** [comment]
merge the remote branches

**Comment by v-leonhou** [comment]
merge remote branch

**Comment by jim-parry** [comment]
wtf? you have branches messed up!

**Comment by v-leonhou** [comment]
oh, sorry , it is  my fault

**Comment by jim-parry** [comment]
oops!

**Pull request closed without merging**
