### PR TITLE
fix some errors on error_exception.php

### PR DESCRIPTION
**Pull request by ridho1991**
fix some errors related to request & response on error_exception.php

### CODE REVIEW

**Comment by startbbs** [comment]
hope to fix this bug soon!!

**Comment by ridho1991** [comment]
Yes, you're correct. But, $headers will contain array if we do a POST request.

```
Array
(
    [Content-Type] => Array
        (
            [0] => CodeIgniter\HTTP\Header Object
                (
                    [name:protected] => Content-Type
                    [value:protected] => multipart/form-data; boundary=----WebKitFormBoundaryUySNXbRhRi3diH2u
                )

            [1] => CodeIgniter\HTTP\Header Object
                (
                    [name:protected] => Content-Type
                    [value:protected] => multipart/form-data; boundary=----WebKitFormBoundaryUySNXbRhRi3diH2u
                )

        )

    [Cookie] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Cookie
            [value:protected] => debug-bar-state=minimized; 60073c17a69bb94bb1f7470c078d8173=ID; 6f68e447328a254d01408c4d22d81aec=114.120.239.212
        )

    [Accept-Language] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Accept-Language
            [value:protected] => en-US,en;q=0.8
        )

    [Accept-Encoding] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Accept-Encoding
            [value:protected] => gzip, deflate
        )

    [Referer] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Referer
            [value:protected] => http://ci4.local/
        )

    [Accept] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Accept
            [value:protected] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        )

    [User-Agent] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => User-Agent
            [value:protected] => Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
        )

    [Upgrade-Insecure-Requests] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Upgrade-Insecure-Requests
            [value:protected] => 1
        )

    [Origin] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Origin
            [value:protected] => http://ci4.local
        )

    [Cache-Control] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Cache-Control
            [value:protected] => max-age=0
        )

    [Content-Length] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Content-Length
            [value:protected] => 285
        )

    [Connection] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Connection
            [value:protected] => keep-alive
        )

    [Host] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Host
            [value:protected] => ci4.local
        )

    [Mod-Rewrite] => CodeIgniter\HTTP\Header Object
        (
            [name:protected] => Mod-Rewrite
            [value:protected] => on
        )

)
```

I see you do a same thing in [this commit](https://github.com/bcit-ci/CodeIgniter4/commit/5adb9ffef5c21531624a8e88365d075cfd1274d6), file toolbar.tpl.php lines 191-200.

But, it's up to you, I will revert back some changes in lines 283-286 to previous state if you wish.

**Comment by lonnieezell** [comment]
Good point. I was likely being lazy on that last fix. :) 

I need to go back through the HTTP spec because it doesn't make sense to me that should work - having 2 headers by the same name. I'm just afraid it's a deeper problem than the toolbar, so will investigate.

**Comment by lonnieezell** [comment]
Alright, just checked the [HTTP Message spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) and the spec does allow for multiple headers with the same field-name, so it looks like we're good to merge this. 

Thanks!

Though it does seem weird that we're getting 2 identical headers on a post request...

**Comment by ridho1991** [comment]
You're welcome :-)

**Pull request merged**
