### PR TITLE
using HTTP\Request instance to pull ip address instead of $_SERVER['REMOTE_ADDR']

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by puschie286** [comment]
i guess its not necessary to create a new config instance each time -> would use config( App::class ) for the global instance. also thing the same should be possible for HTTP/Request instances or are there reasons not to do so?

**Comment by samsonasik** [comment]
using `config(App::class)` will require to define at `App` class property, while it is calling function inside `HTTP\Request` class. The another solution may add new constant inside `application/Config/Boot/*` or `application/Constants.php`

**Comment by puschie286** [comment]
? its the same as you do, but no new instance ( ok you will have to do config( \Config\App::class ), sry for forgetting namespace )

**Comment by samsonasik** [comment]
What I meant is, using new instance in class property is not doable in php, eg;

```php
class App
{
    public $ip = (new Request())->getIpAddress();
}
```
The alternative is by define as constant

**Comment by samsonasik** [comment]
I've updated to set `ipAddress` property in `__construct()` in each of the class that require it.

**Comment by jim-parry** [comment]
@lonnieezell I am good with this. Ok to merge?

**Comment by lonnieezell** [comment]
That's not exactly what I meant. The preferred way to do this is to grab a copy of the IP address in the services class, [where the driver is instantiated](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Config/Services.php#L686) and pass it in the constructor of the driver.

**Comment by samsonasik** [comment]
@lonnieezell implemented

**Comment by samsonasik** [comment]
travis green https://travis-ci.org/bcit-ci/CodeIgniter4/builds/447948785?utm_source=github_status

**Comment by samsonasik** [comment]
as all handlers has ipAddress property, I add ipAddress property to BaseHandler with inject in 2nd parameter.

**Comment by lonnieezell** [comment]
Looks good. Thanks!

**Pull request merged**
