### PR TITLE
URI Routing update

### PR DESCRIPTION
**Pull request by bangbangda**
1.resource method.increase edit and new routes.
2.listAll to index

### CODE REVIEW

**Comment by lonnieezell** [comment]
Can you explain the reasoning behind your changes to the routes? show/edit seem to be about the same thing, just different names. I intentionally kept index free, because many might want to make their REST API's self-documenting by using index as the OPTIONS route.

**Comment by bangbangda** [comment]
yes.There is no clear distinction between show and edit, URI is more friendly. Edit can be deleted.

**Comment by daylightstudio** [comment]
I've seen and used show as a way to present the information in a readonly format. For example, the user profile information without the input fields. It's not as common as edit but definitely has a place.

**Comment by bangbangda** [comment]
ok. PATCH OR PUT mapping to update method.

**Pull request merged**
