### PR TITLE
Update style guide for functions

### PR DESCRIPTION
**Pull request by jim-parry**
What do you think of this style guide update? It clarifies namespaces and camelBack/lowerCamelCase for function naming. 

ps - misnamed my branch ... s/b docs/functions-style

### CODE REVIEW

**Comment by lonnieezell** [comment]
Has there been a decision on any of these items? I thought they were still being discussed on the forums? I know that, currently, I don't think name-spacing them is needed, and after I asked for pros/cons the original poster seemed to agree with me.

I don't really have a strong opinion one way or the other about whether they are camel or snake cased, honestly. They both have their valid reasonings. Snake case matches the rest of the PHP function naming, which seems to be a pretty good reason to keep them that way. I can't speak for why @narfbg originally spec'd them that way, but it seems like a fair reason. 

At the moment we're considering changing this up because one guy has a preference. Not saying we shouldn't consider it, but seems early to change the style guide when no decisions have been made that I'm aware of. Unless, of course, you've decided that's how you'd prefer them. :)

**Comment by jim-parry** [comment]
I proposed the naming case early in the thread in question ... it made sense to me after investigation. The thread got sidetracked, and I am trying to bring it back on track.

Having the same naming convention for standalone functions as for method functions seems most reasonable to me.

The namespacing ... without it, we end up polluting the global functions. I came across several references to this. Static class methods ... no. Cake has some [global convenience functions]([url](http://book.cakephp.org/3.0/en/core-libraries/global-constants-and-functions.html#global-functions)), with really meaningful names (not!).

This PR is meant to collect what seemed to be agreed to ... not a problem to hold off until the situation is clearer :)

**Comment by lonnieezell** [comment]
Ah, yeah, I forgot you suggested that. Like I said - no strong opinions either way for function names. 

I do feel that namespaces would cause usability issues. My personal suggestion is that we leave it in the global space and anyone that wants to "override" can do so in their own namespace.

**Comment by narfbg** [comment]
> Files declaring functions MUST have a name which meaningfully describes the set of functions contained in it.

You're replacing SHOULD with MUST, but at the same time making the rule vague ... It is no longer clear that it is about files containing only standard functions.

And yes, being consistent with PHP itself is one of the reasons why `snake_case` is what I've originally put in there. The other will be mentioned below ...

> also known as *camelBack*

This is the first time ever I see somebody referring to it as "camelBack", I think this will confuse users.

There are indeed different variations of camel case naming, but in the PHP world everybody assumes `camelCase` as the default and says `UpperCamelCase` when referring to the other.

> `camelBack()` the same as method names

I see, consistency makes sense in general. But here's comes in the second argument for `snake_case()` functions ...

Consistency in this case adds cognitive overhead, making it harder to distinguish class methods from functions. It's not practical.

PHP itself has suffered a lot from people obsessing with keeping things the same; it's an argument easy to relate to, but highly subjective - as is evident from this discussion, we differ on what it should be consistent with.

> Scripts containing functions SHOULD have a namespace declaration, consistent with the script's filename. This would be a namespace under `CodeIgniter\` which meaningfully describes the set of functions defined in the script (for instance a CodeIgniter Helper).

I've got two things against this ...

1. It's plain wrong.

    Helper functions are useful because of their conveniently short names. When you force them in a namespace and then have to explicitly `use` them, they become annoying to work with.

2. It doesn't belong in a styleguide.

    It's an architectural decision for the framework, not style.

Also, "pollution" doesn't exist.

**Comment by jim-parry** [comment]
Thank you, narfbg ... that makes sense. I think I jumped to conclusions with the helper thread on the forum. Withdrawing this PR until things settle down more!

**Pull request closed without merging**
