### PR TITLE
add php 7.1 into travis

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please have only one type of change per pull request. In this case, I would be happy to merge the 7.1 addition to travis, but the name changes to variables in the PagerInterface are not related. If you can remove those changes to the interface and just have the travis-related changes I'll be happy to merge.

**Comment by samsonasik** [comment]
I've removed the changes to PagerInterface

**Comment by samsonasik** [comment]
travis now broken as expected.

**Comment by lonnieezell** [comment]
I'll have to look at this later, but the error it's getting is strange since it's showing the new PHP 7.1 optional marker as in the PagerInterface, but it's not.

```
Declaration of 
CodeIgniter\Pager\Pager::links(string $group = 'default', string $template = 'default_fu...'): string must be compatible with 
CodeIgniter\Pager\PagerInterface::links(string $template = 'default', ?string $group = NULL): string in /home/travis/build/bcit-ci/CodeIgniter4/system/Pager/Pager.php 
```

I'm not aware of any changes to 7.1 that would cause a BC break on that method declaration.

**Comment by lonnieezell** [comment]
Though I did just notice the arguments are backwards between the interface and the implementation. Oops.

**Comment by samsonasik** [comment]
I've created PR #362 for PagerInterface signature fixes

**Pull request merged**
