### PR TITLE
Library to Manipulate array as Table.

### PR DESCRIPTION
**Pull request by giriannamalai**
I have implemented an Array manipulation library which works similar to Codeigniter Query Builder. 
Consider Associate/result array as an table and library can handle it.
This feature is really required one too.
It will help us reduce repeated calls of mysql. 
[Read ](https://github.com/giriannamalai/Arrayz/blob/master/README.md) this to know more about the features include within the library.

As a codeigniter user, I want to contribute my work for the forth development. Please review and let me know.
Thanks...!

### CODE REVIEW

**Comment by lonnieezell** [comment]
First off - looks like a very cool library with some pretty thorough features. Probably a lot of work put into that, nice job! 

That being said, I'm not convinced that's right for the core framework. What do you think @jim-parry ?

**Comment by jim-parry** [comment]
Interesting library, for sure. I agree - it doesn't fit with the framework at the moment.
It could be an interesting third-party addin.

**Comment by giriannamalai** [comment]
@lonnieezell  @jim-parry  Thanks...! :smile: 
Understood. It can fit as a library. It's also nice.
And I have an idea, Is it possible..., CI can create a section for all kind of third-party add on/libraries, in CI repo/guide? 
We know composer is good. But if its available directly in CI that will be help everyone too.. :smiley:

**Comment by jim-parry** [comment]
We plan an addins section on our website. Putting third party addins into the main repo/guide is the same as including them with the framework - they need to be external.

**Comment by giriannamalai** [comment]
Ok. understood...! @jim-parry

**Pull request closed without merging**
