### PR TITLE
WIP Fix docs re PHP server

### LINKED ISSUE #1240: Route in the News Tutorial Routes are ERROR all over.
Doing the News Tutorial since you changed the routing of the controller.

All the routes are giving a 404 error unless I change them from get and post to add.

Also the create method is throwing a expected array error on the request.
Lonnie something is wrong in the new way the routes and requests are working.

### PR DESCRIPTION
**Pull request by jim-parry**
It looks like the PHP builtin server isn't very useful with CI4, as it doesn't process .htaccess files :(

### CODE REVIEW

**Comment by lonnieezell** [comment]
The `php spark serve` command takes care of that limitation by providing a mod_rewrite type functionality...

**Comment by jim-parry** [comment]
Hmm - maybe that should be mentioned in the tutorial :-/
I'm playing with it.

**Comment by jim-parry** [comment]
The tutorial still needs changing. I haven't found a bug in the code yet, but haven't finished playing.

**Comment by jim-parry** [comment]
`php spark serve` helps, but I still get errors trying to serve the default page. /home and /about work fine.

**Comment by lonnieezell** [comment]
Interesting. I haven't pulled down a fresh branch in a while, but I use `serve` for everything when I'm working on CI stuff. Maybe I'll actually have a chance this weekend to look into more.

**Comment by jim-parry** [comment]
Merging this, as it is an improvement though not a solution to the "error" situation going through the tutorial.

**Pull request merged**
