### PR TITLE
Fix cannot use class Honeypot because already in use in App\Filters\Honeypot

### PR DESCRIPTION
**Pull request by samsonasik**
The class named "Honeypot", while it uses `CodeIgniter\Honeypot\Honeypot` class in use statement. Make alias of it as `BaseHoneypot` to avoid conflict.

### CODE REVIEW

**Comment by jim-parry** [comment]
Instead of introducing an alias for Honeypot, why not rename application/Filters/Honeypot to application/Filters/HoneypotFilter ... that seems better suited to the intent of the class.

**Comment by samsonasik** [comment]
@jim-parry I've renamed to HoneypotFilter

**Comment by samsonasik** [comment]
@jim-parry actually, there is already `Services::honeypot()` function in `Config\Services` class, I've updated to : 

```php
$honeypot = Services::honeypot(new \Config\Honeypot());
```

**Comment by jim-parry** [comment]
even better :)

**Pull request merged**
