### PR TITLE
Fix white spaces

### PR DESCRIPTION
**Pull request by kenjis**
Just replaces 4 spaces with a tab.

### CODE REVIEW

**Comment by jim-parry** [comment]
Won't cs-fixer do this automatically? It seems like a silly fix, that will be needed in multiple places, I am sure, until the codebase settles down.

Part of that settling will be securely signed commits, btw (hint, hint)

**Comment by jim-parry** [comment]
See the other PR for further comments. This sugegsts that maybe the two should be combined.

**Comment by kenjis** [comment]
> Won't cs-fixer do this automatically?

Unfortunately it seems cs-fixer does not have an option for tab indentation.
As far as I read the documentation.

**Comment by jim-parry** [comment]
Fair enough. Picky but valid PR :)

ps ... look into secure signing ... https://bcit-ci.github.io/CodeIgniter4/contributing/signing.html

**Comment by kenjis** [comment]
@jim-parry 
Oh, I see.
I didn't understand what was *securely signed*. Sorry.

**Comment by jim-parry** [comment]
No worries - it'll take all of us some getting used to!
I am not so worried about "cosmetic" changes, but anythiung affecting the framework codebase would be better securely signed.

**Pull request merged**
