### PR TITLE
add test function for populateHeaders()

### PR DESCRIPTION
**Pull request by BoyDiao**
Signed-off-by:Lin Yang <bcityang@gmail.com>

### CODE REVIEW

**Comment by BoyDiao** [comment]
unit test for populateHeaders() in http/message

**Comment by jim-parry** [comment]
The PR has issues, which we will deal with offline. Then you can resubmit :)

**Comment by lonnieezell** [comment]
Looking at Travis it looks like tests all pass but Travis switched to a new version of Ubuntu which is causing issues with the coverage calculations.

**Comment by jim-parry** [comment]
Ok, so we shouldn't worry too much, so long as it passes unit test locally? There are other problems with the PR that are being fixed :-/

**Pull request closed without merging**
