### PR TITLE
Add leading \ before function invocation of internal function to speed up resolving.

### PR DESCRIPTION
**Pull request by samsonasik**
refs: 
- https://wiki.php.net/rfc/fallback-to-root-scope-deprecation
- https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

applied with php-cs-fixer with `native_function_invocation` rule

### CODE REVIEW

**Comment by samsonasik** [comment]
I'm not sure about travis build error: 
```
There were 2 errors:
1) CodeIgniter\HTTP\Files\FileCollectionTest::testMoveWhereOverwriteIsFalseWithMultipleFilesWithSameName
CodeIgniter\Files\FileException: The original file is not a valid file.
/home/travis/build/bcit-ci/CodeIgniter4/system/HTTP/Files/UploadedFile.php:165
/home/travis/build/bcit-ci/CodeIgniter4/tests/system/HTTP/Files/FileCollectionTest.php:440

2) CodeIgniter\HTTP\Files\FileCollectionTest::testMoveWhereOverwriteIsTrueWithMultipleFilesWithSameName
CodeIgniter\Files\FileException: The original file is not a valid file.
/home/travis/build/bcit-ci/CodeIgniter4/system/HTTP/Files/UploadedFile.php:165
/home/travis/build/bcit-ci/CodeIgniter4/tests/system/HTTP/Files/FileCollectionTest.php:500
```

**Comment by jim-parry** [comment]
We should NOT change anything in system/ThirdParty - that is code pulled in through Composer, and is not ours to fix.

**Comment by samsonasik** [comment]
that previously debug the travis error, as it changed kint file, but seems not related, I can revert it to change ThirdParty/ back

**Comment by samsonasik** [comment]
I already reverted the change of ThirdParty directory at https://github.com/bcit-ci/CodeIgniter4/commit/7dc7655a9bbd8875bda189de6f197a25453cf508

**Comment by lonnieezell** [comment]
I get that this might have a tiny performance gain, but is nasty to work with on a day-to-day basis. :) 

As for the RFC - from the discussions on it, I don't think that has a great shot at happening any time soon. 

Personally, I'm a -1 on this, unless you can prove that the performance gains are worth the developer pain.

@jim-parry thoughts?

**Comment by jim-parry** [comment]
The RFC is *proposed* for PHP7.3 - we should not be jumping on that bandwagon while still only requiring 7.1, given the extent of the changes needed to satisfy it. 
It might be appropriate to re-examine the issue, once CI4 is feature complete, and if the RFC is approved.
It looks like you used a tool to do this, so it should be easily redone if/when appropriate.

**Comment by samsonasik** [comment]
Yes, ok, i’m closing it for now

**Pull request closed without merging**
