### PR TITLE
Updated system files to make them inline with the rest of the framework

### PR DESCRIPTION
**Pull request by coderste**
The namespace for the URI.php file was on a different line to the opening PHP tag. Moved this back inline with the PHP tags to bring it inline with the rest of the files

### CODE REVIEW

**Comment by jim-parry** [comment]
I am not convinced this needs to be a PR on its own. The assumed convention doesn't appear to be addressed in our style guide, although it is probably a good idea.
An entire PR for this seems silly - such a change should be incorporated at the time of other changes, no?

**Comment by jim-parry** [comment]
I see that the PR was premature & didn't include all the proposed changes.
Adding missing comment headers is reasonable.
As for the namespace, is that something that should be addressed in the style guide, @lonnieezell ?

@coderste Consistency is good, but not everyone has their IDE formatting configured that way.
I objected to a PR changing a single file to move the namespace to the opening php tag.

**Comment by jim-parry** [comment]
@coderste We do not attempt to conform to the PSR standard, unless so mentioned in our style guide :-/

**Comment by coderste** [comment]
Yea I notice that, and that't why I changed the title back. Also I think this is a reasonable PR as there were files missing the headers and while I was fixing the headers I fixed the namespace issue at the same time - I suppose it's up to you guys on what you want to do just trying to keep everything consistent :)

**Comment by jim-parry** [comment]
Consistency is good :)
It also sounds like there are a few things to add to the style guide ... the namespace placement, and braces for a class declaration. There are probably a few more.
We recognize that the formatting can be problematic, and were hoping to integrate a style checker or fixer into travis-ci so that we wouldn't have a series of PRs competing with each other to impose anyone's interpretation of the style guide.

Re braces placement, Lonnie said in my last PR that "Braces should be on lines by themselves."

**Comment by coderste** [comment]
@jim-parry Yea I saw that comment that's why I went ahead and added the new line for the braces where there weren't one. The first PR you was probably right it didn't seem enough to have a PR but then a spotted more and more files and some files without the header which I think has to be in all our System files by the looks of it.

We should probably update the Style Guide to indicate what we mentioned until we have a Style Checker or fixer for Travis-CI

**Comment by jim-parry** [comment]
The FTP conversion needs to be in a separate PR. Developers would normally use a separate feature branch for that. See https://bcit-ci.github.io/CodeIgniter4/contributing/workflow.html#branching-revisited

Code contributions need to be GPG-signed, to prove provenance. See https://bcit-ci.github.io/CodeIgniter4/contributing/signing.html

Thanks

**Comment by coderste** [comment]
Yea sorry my bad I totally forgot about changing branch for that xD Any way we can revert that?

**Comment by jim-parry** [comment]
You should be able to revert your last commit ... I'm not up enough on that but it seems like you should be able to do a "git revert" locally, then repush your branch. You need to save the changed code from that (eg FTP), so you can make a new branch with it :-/

**Comment by coderste** [comment]
@jim-parry @lonnieezell I don't suppose there is a way to just remove the FTP file from this PR, see I was making the changes while at work now I'm home for the weekend and tried to remove the PR but I don't seem able to.

Sorry about that - new to contributing on Open Source projects I'll be sure not to make the same mistake again :)

**Comment by lonnieezell** [comment]
@coderste Not a problem, I can close this one. :)

**Pull request closed without merging**
