### PR TITLE
set project name in composer.json to codeigniter4/framework

### PR DESCRIPTION
**Pull request by samsonasik**
on next move, we can register at packagist under "codeigniter" package https://packagist.org/packages/codeigniter/

### CODE REVIEW

**Comment by kenjis** [comment]
By the way, what is `codeigniter/hmvc_xajax_ci`?

**Comment by samsonasik** [comment]
I don't know, just see that `codeigniter/framework` exists for ci3

**Comment by lonnieezell** [comment]
`codeigniter/hmvc_xajax_ci` is not an official package and is one put together by someone else. Not overly cool they put it in the `codeigniter` space. 

I'm not 100% sure if this is the naming we'll use. What do you think @jim-parry ?

**Comment by jim-parry** [comment]
That other package is from 2014?, and based on 2.1.4!
It has no business being in the codeigniter namespace, though I don't know how we would go about getting that fixed.

**Comment by kenjis** [comment]
How about asking the author to see if he/she can rename?

**Comment by jim-parry** [comment]
Asked. no response yet.
btw, the PR title suggests using codeigniter/framework4 ... perhaps we should use codeigniter4/framework instead, to provide a "namespace" for namespaced goodies intended for CI4 :-/

**Comment by samsonasik** [comment]
@jim-parry updated to codeigniter4/framework

**Comment by jim-parry** [comment]
I got in touch with the packagist maintainer, and he removed the other package. "codeigniter" is an official vendor namespace now.
I suggest that we move on adding "codeigniter4/...", and claim that vendor namespace too.

**Pull request merged**
