### PR TITLE
Fix router file dependency

### PR DESCRIPTION
**Pull request by ytetsuro**
I wanted to place the Controller classes outside the `application/Controllers` directory.
This eliminates dependency on the file of `Router class`.

### CODE REVIEW

**Comment by lonnieezell** [comment]
If you namespace your classes, it should all work just fine and you place the controllers wherever you want them to. This PR isn't necessary.

**Comment by ytetsuro** [comment]
Thank you for your reply!

Suppose that an application Foo using CodeIgniter 4 was born.
The controller directory of Foo is as follows.

```
application
└── Controllers
    └── Bar.php
```

I would be able to do the following if you wanted to modify Foo's source code at that time without making any changes

```
Foo
└──application
    └── Controllers
        └── Bar.php
MyAPP
└──application
    └── Controllers
        └── Bar.php
```

All we have to do is rewrite `Config/Autoloader.php`

**Comment by lonnieezell** [comment]
Again, you should be able to do that already. If not namespaced, controllers are expected to be found in application/Controllers, which both of your examples show. If you're wanting to share between two applications, you would simply namespace the controllers, and then define the namespaced controller in your routes. 

I'm unsure, honestly, what you're trying to accomplish that isn't already possible. In your example, you just have two separate applications in subfolders.

**Comment by ytetsuro** [comment]
Sorry.
We did not consider cases where namespace does not exist.

Thank you very much.

**Pull request closed without merging**
