### PR TITLE
new migration strategy

### PR DESCRIPTION
**Pull request by baselbj**
fix all issues and add support migrations per module. The idea is to make the migration class supporting migration per module so that each module (Namespace) have it's own versioning sequence.

### CODE REVIEW

**Comment by baselbj** [comment]
Hi,

Please Review my changes and comments, the setPath() function is changed to be setNamespace()

**Comment by baselbj** [comment]
I can build a new unit test if needed

**Comment by lonnieezell** [comment]
Sorry - work has me with 2 deadlines this upcoming week which has left me working every night for the last couple of weeks. After this next week, I'll be back and more active on CI4. 

Yes, we'll need to tests updated for this, and the docs as well, please. 

I know there are some other issues with Travis at the moment that I'm trying to figure out, so just make sure all of the related tests to this are in place and passing and don't worry about the unrelated errors that Travis shows.

**Comment by baselbj** [comment]
I will read about your testing strategy and do it ... please contact me if you need any help I am now nearly free :)

**Comment by baselbj** [comment]
Hi,

I don't know what is the problem with postgresql as It works with mysql ... please note that I added  new field (namespace) in migrations table:
protected function ensureTable()
    {
        if ($this->db->tableExists($this->table)) {
            return;
        }

        $forge = \Config\Database::forge();

        $forge->addField([
            'version' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => false
            ],
            'group' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => false
            ],
            'namespace' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => false
            ],
            'time' => [
                'type' => 'INT',
                'constraint' => 11,
                'null' => false
            ]
        ]);

**Comment by lonnieezell** [comment]
@baselbj If you click through the errors on Travis you'll get to [this page](https://travis-ci.org/bcit-ci/CodeIgniter4/jobs/208025560) which shows the output. Looks like you've got an uppercase `N` for Namespace in the tests, but the column name is built lowercase. And MySQL does a lot of its comparisons case-insensitive. Seems that Postrgre doesn't like that.

**Comment by lonnieezell** [comment]
Looking pretty good. Thanks!

**Comment by baselbj** [comment]
Your welcome i will check feeds now

**Comment by baselbj** [comment]
Hi;

I think we need to check the migration documentation I think some the points I added needs to be fixed. and I cant find the class reference.

and As I am new to this github world I didn't find a good tool to test my documentation update. can I check them from the browser on my local machine ?

**Pull request merged**
