### PR TITLE
Merge pull request #1 from bcit-ci/develop

### PR DESCRIPTION
**Pull request by ravi2katre**
uptodate

Each pull request should address a single issue, and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345
- Unsolicited PRs will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

### CODE REVIEW

**Comment by ravi2katre** [comment]
commit

**Comment by ravi2katre** [comment]
ok

**Comment by ravi2katre** [comment]
okkkk

**Comment by jim-parry** [comment]
I also note that you checked "signed commit", whereas yours wasn't.

**Pull request closed without merging**
