### PR TITLE
Config helper

### PR DESCRIPTION
**Pull request by puschie286**
config helper implementation for #1071 

Signed-off-by: Christoph Potas <christoph286@googlemail.com>

### CODE REVIEW

**Comment by lonnieezell** [comment]
Looks good. Please add docs and some tests for the class please, and then we are good to go.

**Comment by jim-parry** [comment]
Something is broken in the travis-ci unit tests.
This PR actually did not pass the tests ... I get the following when I run it locally:

> 1) CodeIgniter\Config\ConfigTest::testCreateSingleInstance
> Failed asserting that null is an instance of class "Config\Email".
> 
> /pub7/htdocs/CodeIgniter4/tests/system/Config/ConfigTest.php:14
> 
> 2) CodeIgniter\Config\ConfigTest::testCreateSharedInstance
> Failed asserting that false is true.
> 
> /pub7/htdocs/CodeIgniter4/tests/system/Config/ConfigTest.php:31

Looking at the travis-ci results, it shows an error and four failures, but then echos "Hello World" at the end of the row after 1403/2089 and then exits with "success" !?

**Comment by jim-parry** [comment]
ps - the error and two failures outside of ConfigTest show in other PRs, and were not caused by this PR.

**Comment by puschie286** [comment]
Hmm, the tests passed locally - it’s pretty weird, not sure what’s the different between our installation that can cause this.

**Comment by jim-parry** [comment]
Are you perchance running on WIndows locally?

**Comment by puschie286** [comment]
Yes
  

  
  

  
  
>

**Comment by jim-parry** [comment]
Oops. You will find Config::get('email') because WIndows is case-insensitive. Linux won't find it, hence the test fails.
Lines 10 & 28 in your test will not return a class on Linux.

**Comment by puschie286** [comment]
Oh, so i can’t handle lower case class names at all.
I will push the needed changes tomorrow.

**Comment by jim-parry** [comment]
The alternative is to UCfirst the class name that results, which should work on all platforms.

**Comment by puschie286** [comment]
hmm, the internet says no -> php is **not** case sensitive for classes [SO](https://stackoverflow.com/questions/5260168/capital-letters-in-class-name-php)

i guess the filenames are the problem, because we are loading them directly.

**Comment by jim-parry** [comment]
It is not a classname case sensitivity, it is a filename case sensitivity problem.
If you have a file AbCdEf.php, containing a PurpleDragon class definition, then you can load it as "abcdef.php" on Windows, but you need to use the correct filename case on Linux, or the source file will not be found.
Once loaded, you can then instantiate purpledragon or PURPLEdragon or whatever :-/
The example here is purposeful, to highlight the different issues.

**Pull request merged**
