### PR TITLE
Updated .gitignore - add phpintel to Sublime Text

### PR DESCRIPTION
**Pull request by coderste**
PHP Intel is a folder created by a Sublime Text PHPIntel extension which enable PHP auto-complete for functions and objects

### CODE REVIEW

**Comment by jim-parry** [comment]
Separate branch :)

Signed off, but not GPG-signed... not a problem for this (no code), but perhaps a symptom of a misconfig?

The .env and /results/ included in your .gitnore suggest that you might not have synched your develop branch before pushing your patch branch.

**Comment by coderste** [comment]
Probably not signed off as I edited the file directly from GitHub as it was such a small change :)

About the .env and /results/ I was editing directly from the develop branch that was no commits behind so not to sure what you mean by this

**Comment by jim-parry** [comment]
Not a problem. Not sure then why the .env and /results/ showed up, as they should have already been there :-/

**Comment by coderste** [comment]
The .env showed up because I reordered that section and the /results/ I'm assuming because it got knocked down 1 line maybe?

**Comment by jim-parry** [comment]
Yes, that makes sense. Not to worry :)

**Pull request merged**
