### PR TITLE
Corrects Log Levels

### PR DESCRIPTION
**Pull request by lucanos**
The previous listing of Log Levels was not in alignment with the published [PSR-3 Log Levels](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#5-psrlogloglevel)

### CODE REVIEW

**Comment by lonnieezell** [comment]
The ordering of the values within the Logger class makes no difference on PSR compliance. They were ordered the way they were to work the [threshold](https://bcit-ci.github.io/CodeIgniter4/general/logging.html#configuration) system that is unique to CI.

**Comment by lucanos** [comment]
The suggested change in order is for that very reason - to ensure that the threshold system within CodeIgniter allows the User to see log events of a higher importance than the specified threshold.

I am happy to be educated on why this decision was made, but I see zero benefit in making "Debug" messages a higher importance than "Warning", "Notice" or "Info", especially considering the fact that (at least in CI3) in routine operation, CI floods with "Debug" messages. This would see "Warning", "Notice" and "Info" events being lost in the noise.

Please reconsider this decision.

**Comment by lonnieezell** [comment]
Ah - well that's a completely different argument than the issue was opened with. :) 

It was created to keep the current CI3 threshold system in place, honestly. However, if you're trying to debug something, it's often helpful to see the warnings and notices that are thrown by the language itself. I imagine that's why it was created that way in the first place. 

In CI4, you do have the option to specify the exact levels you want to see: 
```
// Log only debug and info type messages
public $threshold = [5, 8];
```

**Comment by lucanos** [comment]
Hey Lonnie,

I know that it is possible to set the threshold to an array of values. That is also present in CI3.

The crux of my position is that the PSR-3 scale makes sense to me, in the progression of importance from Debug to Emergency. Having the CI scale mirror that is ideal.

Of course, any scale is useless if the information being attached to that scale is not placed at the right levels, and I know that alot of the CI3 core seems to think that, even in the very limited scale of "debug/info/error" routing activities such as templates being loaded are classified as "info" meaning that, in order to have effective debugging, a user either wades through reams of noise, comments out all those lines in the core (waiting for them to be overwritten with the next update), or makes even their lowest debug messages "error" level, which doesn't make sense.

I love logs for figuring out what is happening under the hood. The PSR-3 scale gives so much granularity and a clear scale, and, currently working in CI3, the dream of using that scale is the only reason I am persisting with CI altogether.

**Pull request closed without merging**
