### PR TITLE
Fix tutorial

### PR DESCRIPTION
**Pull request by kenjis**
Just fixes white spaces.

### CODE REVIEW

**Comment by jim-parry** [comment]
Legitimate defect, but same comment as the other PR...

Won't cs-fixer do this automatically? It seems like a silly fix, that will be needed in multiple places, I am sure, until the codebase settles down.

Part of that settling will be securely signed commits, btw (hint, hint)

**Comment by jim-parry** [comment]
Comment for both PRs: When I replace spaces with a tab inside a .rst document in NetBeans, the tab is automatically converted to spaces. I do not have an option to have settings for rst files.

Would we not want to use spaces for indentation inside RST?

Having said that, the user guide formatting for code examples in the tutorial seems to render fine except for the "static pages". Why do the others need to be changed?
These are examples - if someone copies & pastes, they will have to reformat to suit their editor/style etc.

**Comment by kenjis** [comment]
According to <http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#whitespace>
> Spaces are recommended for indentation, but tabs may also be used. Tabs will be converted to spaces. Tab stops are at every 8th column.

It seems it is better not to use tab in RST.

> Having said that, the user guide formatting for code examples in the tutorial seems to render fine except for the "static pages". Why do the others need to be changed?

We don't have to change, but I just want to use the same indentations. If we use tabs, we always use tabs. If we use spaces, we always use spaces.

**Comment by jim-parry** [comment]
Ok - it sounds like tabs are inappropriate, so closing this PR.
The formatting for 3 of the 4 pages in the tutorial renders fine, but the "static pages" one is a bit messed up, and fixing that (with spaces) would be good.

**Pull request closed without merging**
