### PR TITLE
Remove invisible character

### PR DESCRIPTION
**Pull request by vibbow**
Remove invisible character

**Checklist:**
- [ N ] Securely signed commits
- [ N/A ] Component(s) with PHPdocs
- [ N/A ] Unit testing, with >80% coverage
- [ N/A ] User guide updated
- [ N/A ] Conforms to style guide

### CODE REVIEW

**Comment by jim-parry** [comment]
What invisible charater are you referring to? 
Nothing shows on my system, when inspected a couple of different ways.

**Comment by vibbow** [comment]
screenshot

It can be seen by `beyond compare` or `visual studio code` or `notepad++`.

**Comment by jim-parry** [comment]
Good catch. 
Future commits should be GPG-signed, thanks.

**Comment by vibbow** [comment]
> 
> 
> Good catch.
> Future commits should be GPG-signed, thanks.

Yes, tring to figure out how to setup those thing on windows.

**Pull request merged**
