### PR TITLE
Error in user guide for session config. Fixes #1330

### LINKED ISSUE #1330: Error in user guide for session config
The user guide (libraries/sessions) still describes the CI3 style of configuration (i.e. $sessionDriver = "files" instead of $sessionDriver = 'CodeIgniter\Session\Handlers\FileHandler';

Needs fixing :-/

### PR DESCRIPTION
**Pull request by bangbangda**
**Description**
Fixes issue #1330 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by jim-parry** [comment]
Are you sure that `filter </CodeIgniter4/incoming/filters.html>`_ exists? Wouldn't it just be `filter <incoming/filters.html>`_?

**Comment by bangbangda** [comment]
> Are you sure that `filter </CodeIgniter4/incoming/filters.html>`_ exists? Wouldn't it just be `filter <incoming/filters.html>`_?

The link before change is: https://bcit-ci.github.io/general/filters. not /CodeIgniter4 directory.
so, add /CodeIgniter4 directory I think ok. 
@jim-parry

**Comment by jim-parry** [comment]
CodeIgniter4 should not be there. The link is relative to the other docs generated.
Not the end of the world - I can fix it post-merge.

**Comment by jim-parry** [comment]
I think I see some of the problem. You did not create a feature branch for this, and your "develop" branch also includes some filtering stuff that belongs in another PR. This PR does not conflict, but it addresses more than one thing. Those other changes need to be excluded from this PR, or you might consider doing PRs in feature branches to prevent this from happening.

**Comment by jim-parry** [comment]
each PR should deal with a single issue, so that it can be accepted or rejected in its entirety.
Yes, a PR addressung a different issue should be a separate PR, and we strongly recommend using feature branches to keep the PRs separate from each other.

**Comment by jim-parry** [comment]
From the PR description, and comments, it looks like the only file that should be changed as part of this PR is the user guide page for sessions. The other changes are not related.

**Comment by bangbangda** [comment]
Okay, I understand. Thank you for your explanation.

**Pull request merged**
