### PR TITLE
fix: `highlightFile()` in `BaseExceptionHandler` for PHP 8.3

### LINKED ISSUE #8398: Displaying Error Page with 4.4 with PHP 8.3
### PHP Version

8.3

### CodeIgniter4 Version

4.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL

### What happened?

.env file is set to development but it doesn't display the error page. When I check the development.php file under Config/Boot I see that display_errors is already set to 1. Then, when I set display_errors to 1 in production.php, it shows the error page. However, in the error page there is no error listed. Plus, it detects environment as production.

PHP Version 8.3 (there was no option for this in the selectbox)

CI-Error-php83-v44

BTW, I'm not posting for the security error there. I know, It's because of the CSRF data that I forgot. 

### Steps to Reproduce

nothing

### Expected Output

to be able to display the error page

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
Supersedes #8399
Fixes #8398

This PR fixes issues with `highlightFile()` method.

The source of the problem is the fact that the `highlight_file()` function has slightly changed its behavior in PHP 8.3.

A nice summary can be found here:
https://php.watch/versions/8.3/highlight_file-highlight_string-html-changes

Except for the changes in the `highlight_file()` function, this PR also fixes some issues found in closing opened `span` tags.

I added some changes to the way `$source` variable is handled after noticing @kenjis PR: #8399.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by lonnieezell — APPROVED** [review]

**Comment by kenjis** [comment]
@michalsn `Fixes: #8398` should be `Fixes #8398`.
See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by kenjis** [comment]
```
There were 4 failures:

1) CodeIgniter\Debug\ExceptionHandlerTest::testHighlightFile
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '<pre><code><span class="line"><span class="number"> 9</span> &nbsp;*&nbsp;the&nbsp;LICENSE&nbsp;file&nbsp;that&nbsp;was&nbsp;distributed&nbsp;with&nbsp;this&nbsp;source&nbsp;code.
 <span class="line"><span class="number">10</span> &nbsp;*/
 <span class="line"><span class="number">11</span> 
-<span class="line"><span class="number">12</span> </span><span style="color: #f1ce61;">namespace&nbsp;</span><span style="color: #c7c7c7">Tests\Support\Controllers</span><span style="color: #f1ce61;">;
+<span class="line"><span class="number">12</span> </span><span style="color: #f1ce61;">namespace&nbsp;</span><span style="color: #c7c7c7">Tests</span><span style="color: #f1ce61;">\</span><span style="color: #c7c7c7">Support</span><span style="color: #f1ce61;">\</span><span style="color: #c7c7c7">Controllers</span><span style="color: #f1ce61;">;
 <span class="line"><span class="number">13</span> 
-<span class="line"><span class="number">14</span> use&nbsp;</span><span style="color: #c7c7c7">CodeIgniter\Controller</span><span style="color: #f1ce61;">;
+<span class="line"><span class="number">14</span> use&nbsp;</span><span style="color: #c7c7c7">CodeIgniter</span><span style="color: #f1ce61;">\</span><span style="color: #c7c7c7">Controller</span><span style="color: #f1ce61;">;
 <span class="line"><span class="number">15</span> 
 <span class='line highlight'><span class='number'>16</span> class&nbsp;Hello&nbsp;extends&nbsp;Controller
 </span></span><span style="color: #c7c7c7"></span><span style="color: #f1ce61;"></span><span style="color: #c7c7c7"><span class="line"><span class="number">17</span> </span><span style="color: #f1ce61;">{

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Debug/ExceptionHandlerTest.php:257
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

2) CodeIgniter\Helpers\TextHelperTest::testHighlightCode
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<code><span style="color: #000000">
-<span style="color: #0000BB">&lt;?php&nbsp;var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">);&nbsp;</span><span style="color: #0000BB">?&gt;&nbsp;</span>
+'<code><span style="color: #06B">
+<span style="color: #c7c7c7">&lt;?php&nbsp;var_dump</span><span style="color: #f1ce61;">(</span><span style="color: #c7c7c7">$this</span><span style="color: #f1ce61;">);&nbsp;</span><span style="color: #c7c7c7">?&gt;&nbsp;</span>
 </span>
 </code>'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Helpers/TextHelperTest.php:273
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

3) CodeIgniter\Test\IniTestTraitTest::testBackupAndRestoreIniValues
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'#0000BB'
+'#c7c7c7'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Test/IniTestTraitTest.php:32
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

4) CodeIgniter\View\ParserFilterTest::testHighlightCode
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<code><span style="color: #000000">
-<span style="color: #0000BB">Sincerely&nbsp;</span>
+'<code><span style="color: #06B">
+<span style="color: #c7c7c7">Sincerely&nbsp;</span>
 </span>
 </code>'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/View/ParserFilterTest.php:204
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

--

There were 2 skipped tests:

1) CodeIgniter\Debug\ExceptionsTest::testDeprecationsOnPhp81DoNotThrow
PHP >= 8.1 is required.

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Debug/ExceptionsTest.php:58
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Debug/ExceptionsTest.php:58
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

2) CodeIgniter\Test\TestCaseTest::testPHPUnitHeadersEmitted
CodeIgniter\Test\CIUnitTestCase::assertHeaderEmitted() requires xdebug.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:512
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:417
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Test/TestCaseTest.php:98
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

FAILURES!
Tests: 5012, Assertions: 8463, Failures: 4, Skipped: 2.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7422018813/job/20196514237?pr=8401

**Comment by michalsn** [comment]
Yes, I'm not sure why it fails on PHP 7.4... and I don't have it locally to test 😐

**Comment by michalsn** [comment]
Silly me... the result for PHP 7.4 is slightly different again. Fixed.

**Review by kenjis — APPROVED** [review]
LGTM! Thank you.

**Pull request merged**
