### PR TITLE
Add most of function tests for Config/Services.php

### PR DESCRIPTION
**Pull request by BoyDiao**

### CODE REVIEW

**Comment by jim-parry** [comment]
Why are you changing CodeIgniterTest too? If appropriate, that should be a separate PR, no?
While looking at CodeIgniterTest, I notice that your formatting seems a bit messed up, making its inclusion in your PR seem even more of an accident.

**Comment by BoyDiao** [comment]
This commit I fix all format problems, no?
https://github.com/bcit-ci/CodeIgniter4/pull/521/commits/e102d00d6556d2b19f6152b0179ee6fbbd4d371f

**Comment by jim-parry** [comment]
@lonnieezell  when I try to check these out on my system, all of the ServiceTest methods blow up running PHPunit with:

`PHP Fatal error:  Method PHPUnit\Framework\ExceptionWrapper::__toString() must not throw an exception, caught ErrorException: Undefined index: SCRIPT_NAME in phar:///usr/local/bin/phpunit/phpunit/TextUI/ResultPrinter.php on line 0`

Have you seen this before? Any suggestions on what I am doing wrong or have misconfigured? Thanks!

**Comment by lonnieezell** [comment]
@jim-parry I haven't seen that before. What version of PHPUnit are you using? 

I pull down on my machine to test and they run fine. They also passed on Travis, so I'll probably merge this. I know you're away on vacay.

**Pull request merged**
