### PR TITLE
Revise view section(s) in user guide

### LINKED ISSUE #181: View: saveData
Shouldn't the View::render() $saveData parameter default to true?
$options / $saveData is not used (per phpdocs) and is not in the user guide, which means that $data will be cleared on rendering the way it sits, and that view parameters cannot be passed to successive views.

### PR DESCRIPTION
**Pull request by jim-parry**
Split the view page into several, as it is getting long!
Addressed options explicitly, making it clear they are used.
Closes #181

### CODE REVIEW

**Comment by jim-parry** [comment]
Anything to add to this? or to change?
The separate view user guide pages may seem awkward, but I expect that to be sorted out in the fall when we revisit the documentation structure.

**Comment by mixinix** [comment]
I suggesting to remove old CI2 top menu and upgrade sphinx_rtd_theme.

**Comment by jim-parry** [comment]
@mixinix  The sphinx theme will probably be updated in the fall, when we revisit the guide as a whole. That is not something for a specific update.
As to the "CI2" top menu, we had a large # of complaints that it was missing from CI2, and requests to reinstate it. The CI3 one may look the same, but is dynamically constructed in javascript, and we have kept that for CI4. It oculd be appropriate to revisit that, but again as part of an overall user guide evaluation, not a specific section of it.
Stay tuned in the fall, and get your opinions in :)

**Comment by lonnieezell** [comment]
Looks pretty good. And the 4 views files is definitely reminiscent of the Rails guides. :) 

Looking at this, I don't know that I mentioned anywhere that you could load a view in a namespaced manner. Could have sworn I went back and added that, though.

**Comment by jim-parry** [comment]
Namespaced views are there, about line 88 in views.rst :-/

**Comment by mixinix** [comment]
I'm using Python 3.5.x to generate the userguide. Getting an error with sphinxcontrib-phpdomain.

**Comment by mixinix** [comment]
I think CI 2 top menu can be changes with 'accordion menu' like bootstrap as sidebar. Old CI 2 top menu not responsive.

**Comment by ridho1991** [comment]
@mixinix I think you should use python 2.7.x. See [this guide](https://github.com/bcit-ci/CodeIgniter4/tree/develop/user_guide_src)

**Comment by mixinix** [comment]
No. Problem solved when I remove sphinxcontrib-phpdomain in conf.py. The new version sphinx-rtd-theme looks better.

**Comment by jim-parry** [comment]
@mixinix @ridho1991 This PR was about some view page changes, NOT about the menu or user guide style. Bring those up on the forum, or in an issue, or wait until we review the user guide structure in the fall!

**Comment by mixinix** [comment]
Ok! This is the last one. Sorry :)

**Pull request merged**
