### PR TITLE
feat: remove `pre-commit`

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR removes `pre-commit` and all related code.

While the idea of `pre-commit` was a good one, IMO today it brings developers more problems than good. The number of errors that can occur, even if we haven't touched some files, is simply too high. This can cause many users (even experienced ones) to abandon the changes they are preparing and not send a PR. 

A side effect may be that maintainers will have more work to do in handling PRs, but it's worth the risk.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by paulbalandan — APPROVED** [review]
I agree to this change. In fact, when committing in vscode, I always use the `--no-verify` option and let Github Actions do the job.

**Review by lonnieezell — APPROVED** [review]
Thank you for this. My only other thought was that we had a message reminding about the commands they can run on commit but that's not necessary and can be done later if desired.

**Comment by sfadschm** [comment]
Regarding the extra work for the maintainers I believe to have seen bots respond to PRs in other repositories, where they automatically call out the failed CI Checks and give hints on how to fix.

Like:
"Code style check failed. Please run php-cs-fixer..."

If this is possible it could replace the very frequent comment of "Please fix the coding style", "Commits must be signed" and so on.

**Comment by kenjis** [comment]
I use it. But if you all agree, I don't disagree.
But the current checks are so basic that I don't see why even @paulbalandan is disabling it.

**Review by kenjis — DISMISSED** [review]

**Comment by kenjis** [comment]
@michalsn Can we keep `pre-commit` and `setup.sh`?
If they are installed automatically, there is no harm.

**Comment by michalsn** [comment]
@kenjis So you only want to remove it from the `composer.json` so people can apply it manually? Since you seem to actively using it - sure.

> But the current checks are so basic that I don't see why even @paulbalandan is disabling it.

For a couple of days, we had our checks failing on the `develop` branch. I also remember a few cases when errors pop up when we change unrelated things. All these cases would prevent users from sending a PR. Not everyone knows how to skip verification or remove pre-commit entirely. At this point, this seems to be an issue for contributors.

**Comment by kenjis** [comment]
@michalsn Yes, thanks.
The recent php-cs-fixer errors are caused by the update of cs-fixer.
Unfortunately it happens sometime these days.

I agree with making the hook opt-in.

**Review by kenjis — APPROVED** [review]

**Comment by michalsn** [comment]
Thanks, everyone!

**Pull request merged**
