### PR TITLE
Support resource route when function with subdirectory.

### PR DESCRIPTION
**Pull request by wuzheng40**
In my project, I nedd to implement a new resource api with subdirectory.
I failed use default function to do it. So I modify it.

Support resource route when function with subdirectory.
example: $routes->resource('Admin/Admins');

### CODE REVIEW

**Comment by lonnieezell** [comment]
Looks good. Can you add a test for this to the [RouterTest](https://github.com/bcit-ci/CodeIgniter4/blob/develop/tests/system/Router/RouterTest.php) class?

**Comment by wuzheng40** [comment]
Hi, @lonnieezell 
When I run phpunit, it report **Fatal error: Default value for parameters with a class type hint can only be NULL in C:\Tools\Wnmp\html\UT\system\Config\DotEnv.php on line 121**.
Many developers meet this issure when their php version is lower than 7.
But my version is 7.0.8 .
untitled

**Comment by noldor** [comment]
check ``php -v`` on command line.
probably php versions are different between cli and web.

**Comment by wuzheng40** [comment]
@noldor Thank you, My cli is 5.6.18, After update, it's work now.
@lonnieezell Hi, Test has been updated.

**Comment by lonnieezell** [comment]
Great. Thanks!

**Pull request merged**
