### PR TITLE
Remove static pages routing

### PR DESCRIPTION
**Pull request by fdjkgh580**
Because it affects normal procedures

### CODE REVIEW

**Comment by lonnieezell** [comment]
First - how does this affect normal procedures? 

Second - removing that completely invalidates [this entire page](https://bcit-ci.github.io/CodeIgniter4/tutorial/static_pages.html) of the tutorial.

**Comment by fdjkgh580** [comment]
Hello, this is the problem I encountered, as shown below:

When used Static Pages Routin
image

When removed Static Pages Routin
image

**Comment by jim-parry** [comment]
This looks related to #1240

**Comment by jim-parry** [comment]
I think the solution is to fix the underlying problem, not mask it by dropping the routing rule.

**Comment by lonnieezell** [comment]
This was fixed in da43a39de5808eb5173b848de197afc57c944239

**Pull request closed without merging**
