### PR TITLE
Fix class constant in view error_exception.php

### PR DESCRIPTION
**Pull request by maks-baum**

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please revise all tests to make sure they run correctly. Though I can't think of what this would break off the top of my head, it seems like something isn't liking it.

**Comment by DavisMiculis** [comment]
I tried this, and worked for me okay, showed `4.0-dev`. Don't know why test failed tho.

**Comment by lonnieezell** [comment]
Don't know why it was showing an error. Pulled it down manually and checked it out and all was fine. Thanks for the PR.

**Comment by maks-baum** [comment]
I ran all tests without any errors :/

**Pull request merged**
