### PR TITLE
add more timing constants

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by lonnieezell** [comment]
Is lustrum and indiction still in common use today? I wasn't familiar with them so had to go look them up and it sounds like they were in use during height of the Roman empire and during some of the Medieval period. If it's not in common use today, we don't need to include. They're meant to be helpers, not a definitive set of periods :)

I'm also on the fence about decade and millenium. I think the frequency of use of the latter is probably close to nil, or at least close enough to not be a helpful addition.

**Comment by benedmunds** [comment]
I tend to agree with @lonnieezell here.  Best to only do the common ones.  

I think DECADE is definitely a good addition.

**Comment by samsonasik** [comment]
I removed lustrum, indiction, century, millenium, keep decade

**Comment by benedmunds** [comment]
👍 from me

**Pull request merged**
