### PR TITLE
correcting sphinx format in general/logging.rst

### PR DESCRIPTION
**Pull request by ridho1991**
Continuing text must be aligned after the bullet and whitespace.

### CODE REVIEW

**Comment by jim-parry** [comment]
Better description & good to see the securely signed commit :)

**Comment by ridho1991** [comment]
I set the GPG key yesterday. :-)

**Comment by mixinix** [comment]
commit -s -m '...'

**Comment by ridho1991** [comment]
@mixinix Yes, I do a "commit" like that

**Comment by mixinix** [comment]
Is there any different with -s and -S ?

**Comment by mixinix** [comment]
Make sure you will be seeing
```
Signed-off-by: yourname <yourmail>
```
when you commit.

**Comment by jim-parry** [comment]
@mixinix "commit -s " adds the "signed off by" message. It can be spoofed, eg  I can signoff as "mixinix". OhOh.
"commit -S" requires that a GPG key be setup for your account, and it binds the commit to your account ... not so easily spoofed :) This is the one we are looking for.
See https://bcit-ci.github.io/CodeIgniter4/contributing/signing.html

**Pull request merged**
