### PR TITLE
text_helper

### PR DESCRIPTION
**Pull request by Portaflex**
Hopefully this is the good one. Thanks.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Looks pretty good. Thanks for all of your work on this. I know it hasn't been the easiest journey. 

I'll go ahead an merge, but in the future, please remember that blank lines are ok. :)

**Comment by lonnieezell** [comment]
Actually, noticed a couple of other things for future reference that I didn't notice at first: 

- config files are now classes and we just create new instances. That way they can easily be extended and located anywhere.
- please use short array syntax `[]` instead of `array()`

**Comment by Portaflex** [comment]
Thank you, Mr. Ezel. The battle with "git push" command took me away from those details. Now that I know how to "push", I'll try to fix them. If you prefer I will change the config ForeignChars.php to be a class. Just one question, ¿instantiating classes instead of requiring files doesn't affect performance?
Thanks.

**Comment by lonnieezell** [comment]
There is a very tiny performance hit when instantiating classes vs just requiring them. But the benefits to us overruled that. 

I've already made the adjustments and merged it back in the repo.

**Pull request merged**
