### PR TITLE
Aerospike Cache Driver

### PR DESCRIPTION
**Pull request by byazrail**
I've been using it for about 4 months. Aerospike Cache Library.
I also wanted to add it here.
I could also add the Aerospike Session Library if I wanted to.

### CODE REVIEW

**Comment by jim-parry** [comment]
Something like this definitely needs to be GPG-signed for consideration.

The travis-ci config needs to have aerospike added, so that your provided unit testing is run. I don't see it in the list of supported services on travis-ci.org.

**Comment by byazrail** [comment]
Travis service on see : https://github.com/aerospike/aerospike-client-php/blob/master/.travis.yml
After reviewing I will add the necessary.

**Comment by byazrail** [comment]
Travis service on not supported.
Close Requests.

**Comment by jim-parry** [comment]
Bummer. You could always make it into an addin and offer it to the community over the forum (for now).

**Comment by byazrail** [comment]
Oke Thank, you.
Do you have the class library you want to insert?
Oracle FTP etc. I use the libraries because.

**Comment by jim-parry** [comment]
I don't understand your question. Oracle/FTP don't seem to have a connection to aerospike.

**Comment by jim-parry** [comment]
if you are thinking of namespace, then Aerospike would make sense, for an "Aerospike" module, with config & drivers inside it.

**Pull request closed without merging**
