### PR TITLE
 Add MemcachedHandler test.

### PR DESCRIPTION
**Pull request by KazuakiM**

### CODE REVIEW

**Comment by lonnieezell** [comment]
This one needs much more description of why you're doing things. I very much appreciate the tests, and the integration with Travis to make that happen. However, in doing so, you've changed the call signature of the `get()` method by removing a parameter that was used by the Predis driver, and there are fairly decent changes in all cache handlers. Please explain why you made those changes, what problem you were running into and if you verified the changes worked as expected across all handlers.

**Comment by KazuakiM** [comment]
*Predis driver*
I wanted to clean the indentation of the code.
You can check this commands result and confirm there is not so much correction.
```bash
git diff <main repository:develop> --ignore-space-change system/Cache/Handlers/PredisHandler.php
```
Sorry about my poor English.
I will reply while translating.
First of all it is the answer to the problem.

**Comment by KazuakiM** [comment]
* check order 
The check order has been updated, 1. Memcached 2. Memcache.

* Support Many location
```$config->memcached``` is one location . I wanted to support many location.
https://github.com/bcit-ci/CodeIgniter4/pull/569/files#diff-f647e487901fb5bb591ecce5083b3c51L76

* Support Row at Memcached
I was testing ```increment```and```decrement``` and got error.
```
ErrorException: Memcached::increment(): Initial value is only supported with binary protocol
```
So I Add support code. 
https://github.com/bcit-ci/CodeIgniter4/pull/569/files#diff-f647e487901fb5bb591ecce5083b3c51R110

* $row option required only Memcache(d).
```$row``` option required only Memcache(d).
So I moved parameter to config file.

* Add data resuponse at getMetaData in FileHandler.php
I adapted Memcached response.

https://github.com/bcit-ci/CodeIgniter4/pull/569/files#diff-8567f229ae45619a0ae45f4b693c3ae4R269
https://github.com/bcit-ci/CodeIgniter4/pull/569/files#diff-f647e487901fb5bb591ecce5083b3c51L302

**Comment by KazuakiM** [comment]
Is it better to divide the pull request?

**Comment by lonnieezell** [comment]
I believe the confusion came in large part because the existing comments say it's only used by PredisHandler, but is actually only used by Memcached, as you found. In that case, I think I'm fine with this for now. 

In the future, if your PR does more than what the title says, please describe what and why to save us all a little time. :)

**Comment by KazuakiM** [comment]
I see it.
I'll be more careful.

**Pull request merged**
