### PR TITLE
Added testAppendBody function to MessageTest.php

### PR DESCRIPTION
**Pull request by jchuo93**
From my test/Message branch, pull request to have the testAppendBody function added to the MessageTest.php file

### CODE REVIEW

**Comment by jim-parry** [comment]
It looks like you didn't synch before submitting this ... it includes some Autoloader and FileLocator changes too?
It looks like you didn't reformat your MessageTest, judging from the uneven & inconsistent (spaces vs tabs) line starts.
The unit test fails inside your test, saying you can't pass something by reference, but I don't see that in your code. Perhaps Lonnie can shed some light on it?

**Comment by jchuo93** [comment]
@lonnieezell Hi, I was wondering if you could help me with the problems occurring with me pull request.

**Comment by lonnieezell** [comment]
Looks like it was my fault, though I don't remember why I would have done this :) In line 101 of CodeIgniter\HTTP\Message it is trying to get the value of parameter 1 by reference. Which it shouldn't be doing. If you could change that line to the following and add it to the PR it should work: 

```
public function setBody($data)
```

**Comment by jchuo93** [comment]
Any ideas to why the coverage failed? Is it because I'm not to synced to the repository?

**Comment by jim-parry** [comment]
The unit testing is passing now. The "failure" is the code coverage, which has apparently decreased slightly :-/

**Comment by lonnieezell** [comment]
I've gone ahead and merged it because I've seen some oddities in the past with the way the coverage is calculated. The tests are passing so that's good enough for me right now. Thanks.

**Pull request merged**
