### PR TITLE
FTP Class reference by CI3 include services

### PR DESCRIPTION
**Pull request by byazrail**
FTP class referenced by CI 3.
This class 1 ~ 2 months ago use started.
old ci 3 ftp class methods.

extra service added.
simple use;
```php
service('ftp')->initialize([
	'hostname'	=> 'blabla.com',
	'username'	=> 'aaa',
	'password'	=> 'bbb',
	'port'		=> 21,
	'passive'	=> true,
	'debug'		=> true,
	'timeout'	=> 90
]);
service('ftp')->connect();
```

help me, build documentation.

### CODE REVIEW

**Comment by jim-parry** [comment]
This could be a useful start, but I strongly recommend that you create a frature branch in your repo for this. If we want to allow several contributors, we might want to create a feature branch for it in the CI4 repo.

**Comment by coderste** [comment]
I would be more than happy to carry on the update with the file like adding return/type hinting and write a few PHPUnit Tests. 

What would be the best way to do this? Create a new PR

**Comment by jim-parry** [comment]
@lonnieezell This looks like a superceded PR, and should be deletable

**Comment by lonnieezell** [comment]
@jim-parry I believe you're correct. Closing.

**Pull request closed without merging**
