### PR TITLE
HTML Helper

### PR DESCRIPTION
**Pull request by prezire**

### CODE REVIEW

**Comment by prezire** [comment]
Oh you're right. I'll find time tomorrow and update those.

**Comment by prezire** [comment]
Hi Ionnieezell. Indentions were updated.

**Comment by lonnieezell** [comment]
Great, thanks! I'll go ahead and merge and we'll deal with any potential issues after that since, unfortunately, there's issues with the tests on Travis that I'm trying to work with them to figure out so everything appears broken here. :(

**Comment by prezire** [comment]
Yes, I noticed that on Travis as well. May I know if the issues were caused on my end?

**Comment by lonnieezell** [comment]
Nope, they weren't. 

It partially ended up being a change on did on migrations that was working locally but wasn't working on Travis. IIRC, that was done right about the time I went on a vacation, and I there was an email or blog post from them I read before vacation that led me to believe it would break our tests anyway, so I missed that causing the errors. That got resolved and MySQL live tests are working now, but Postgres isn't, and I haven't had a chance to get it reinstalled locally to test that out since I put a new SSD in my machine.

**Pull request merged**
