### PR TITLE
Adjust log level to match RFC 5424

### PR DESCRIPTION
**Pull request by sugenganthos**
Log level threshold is adjusted to match RFC 5424.
Set threshold to 'debug' level practically show 'all' debug messages. This usually the developer wants on debugging sessions

### CODE REVIEW

**Comment by lonnieezell** [comment]
This causes a test to fail. Please adjust the test so that it passes again.

**Comment by sugenganthos** [comment]
I have update the Test. But maybe another test will fail. Sorry, I'm newbie in test unit. This CI4 framework has big test file. I still fail to configure in my local server. Don't know what to do. I have ask in forum but no one answer.

**Comment by lonnieezell** [comment]
I believe the other tests that were failing for you were incorrect. We have a couple of tests that randomly fail due to timestamp issues that we haven't fixed quite yet. All tests are passing now. Thanks.

**Comment by sugenganthos** [comment]
The test on my local server is failed says 'class not found' or something. It is broken path. It resolved if I edit every file and put 'include' on absolute path
Note: I install PHPUnit myself, not using composer included with CI

**Comment by lonnieezell** [comment]
Please ask on the forums for help getting PHPunit working for you. This is for tracking bugs.

**Pull request merged**
