### PR TITLE
 auto session start 

### PR DESCRIPTION
**Pull request by bangbangda**
Start automatically when the session is initialized.

Why is it a separate $session->start() ?

Before：
$session = session()->start();
After：
$session = session();

Before：
$session = \Config\Services::session($config);
$session->start();
After：
$session = \Config\Services::session($config);

### CODE REVIEW

**Comment by lonnieezell** [comment]
I wasn't involved in the original architecture of the session stuff, I just ported it over. Looking over the main session class I can't see why we shouldn't do this. However, you should put a check within the `start()` method to check if it's running and exit the method at the very beginning of it so that we don't try to start again.

**Comment by bangbangda** [comment]
if sessions are enabled, but none exists. start() method will be executed.
so. will not repeat start().

Please confirm the `system/Config/Services.php` file for details.

**Comment by lonnieezell** [comment]
> if sessions are enabled, but none exists. start() method will be executed.
so. will not repeat start().

True - assuming everyone plays by the rules. :) Someone can still call `start()` if they didn't bother to read the manual closely enough. Also, there are a number of people already building sites on CI4 so it's a simple solution to safeguard their sites a little bit more.

**Comment by bangbangda** [comment]
OK.I understand.
Update the code this afternoon.

**Comment by bangbangda** [comment]
@lonnieezell 
Code update is complete.

**Comment by bangbangda** [comment]
@lonnieezell

**Comment by bangbangda** [comment]
@lonnieezell 
Hi. is there a Issues with this PR?

**Comment by jim-parry** [comment]
@bangbangda Your PR has conflicts that need to be resolved, before travis-ci can be run, and without considering whether or not it is a good idea to auto-start sessions.

**Comment by lonnieezell** [comment]
@bangbangda You merged in changes to the Model class that are already in core. Those should not be part of this, please remove.

**Comment by bangbangda** [comment]
@lonnieezell yes.deletion is complete.

**Comment by lonnieezell** [comment]
Thanks works for me, Thanks @bangbangda

**Comment by lonnieezell** [comment]
Although I just realized this might wreak havoc on testing... but we'll work that out since session tests already broken.

**Comment by jim-parry** [comment]
Hmmm - I remember a similar PR for CI3, and Andrey argued strongly against auto-starting sessions. Don't remember the reasoning.
I don't know that we want to force sessions on evryone, who will then hve to configure them and deal with the hundreds (or much more) of session files resulting from poor or no garbage collection.

I haven't taken a look at the PR, but I trust that any auto-starting is a configurable option.

**Comment by lonnieezell** [comment]
From what I recall of Andrey's reasoning - autostarting the session on every page load could lead to DOS attacks from the sheer number of session being created and some other related security type issues. Completely agree with those. 

What this PR does, though, is to start the session the first time you request it, instead of asking you to do session->start() immediately afterword. I think it should be fine, as I can't think of any additional actions you'd take with the session library before it's started, and none of the methods in the Session class seemed to provide any benefit prior. 

Unless you can think of any issues with that?

**Comment by jim-parry** [comment]
It might work fine, then. A DOS attack could be averted through a Throttle filter :-/

________________________________________

**Pull request merged**
