### PR TITLE
removes extension in CLI file

### PR DESCRIPTION
**Pull request by thanhtaivtt**

### CODE REVIEW

**Comment by jim-parry** [comment]
not to be too picky, but we expect commits to be GPG-signed :)

**Comment by lonnieezell** [comment]
Can you confirm whether this causes any issues under Windows? That's what I hadn't taken the time to fully investigate, yet.

**Comment by thanhtaivtt** [comment]
It can run in any operator. Like laravel artisan

**Comment by lonnieezell** [comment]
IIRC Windows cmd line doesn't support !# commands, and the path would be different even if did. And I don't think there's any way, just out of the box, to convert a file with no extension into a executable. Granted, it's been a decade since I used Windows, so memory may be foggy. And I know that the Creators Update for Win10 brought full bash support, but that doesn't help anyone pre-update. 

A quick search of the issue and here's what I've found: 

- https://laravel.io/forum/07-21-2016-run-artisan-directly-in-windows
- https://stackoverflow.com/questions/21175570/how-to-install-laravels-artisan

And a few others. So, basically, Windows users will have to use `php ci` or whatever, as will any Mac users who have a PHP in a different path that the !# states, anyway. 

So, I guess I don't have any objections to changing `ci` and `serve, but redirect should keep the extension since it's not a user-callable script. 

We do need to update the docs, though. As a starter, [this page](https://github.com/bcit-ci/CodeIgniter4/blob/develop/user_guide_src/source/general/cli_commands.rst) needs updating to remove the extension from the examples, and provide a note for Windows users that they need to ensure PHP is callable and to add the PATH to their environment, etc. The [local server](https://github.com/bcit-ci/CodeIgniter4/blob/develop/user_guide_src/source/installation/local_server.rst) page would need to be updated, and the rest of the docs would need to be scanned for any place that used a CLI example. 

EDIT: There is a linux command `ci` that this could come into conflict with, so maybe hold off until we determine how to handle that.

**Comment by thanhtaivtt** [comment]
Thank you for letting me develop more knowledge.

**Pull request closed without merging**
