### PR TITLE
php spark serve

### PR DESCRIPTION
**Pull request by natanfelles**
Move the development server to a spark command.

```
Description:
   Launchs the CodeIgniter PHP-Development Server.

Usage:
   serve

Options:
   -php       The PHP Binary [default: "PHP_BINARY"]
   -host      The HTTP Host [default: "localhost"]
   -port      The HTTP Host Port [default: "8080"]
```

### CODE REVIEW

**Comment by deathart** [comment]
I'm enjoying your Pull Request (which I think is perfect).

To say that the last line of the `serve` file I must modify it to  

**Before :**
```php
passthru("{$php} -S {$host}:{$port} -t public/ rewrite.php");
```
**After :**
```php
passthru("{$php} -S {$host}:{$port} -t public/ .../rewrite.php");
```

I have to add ../ before rewrite.php

(Windows)

**Comment by lonnieezell** [comment]
@natanfelles What benefit do you see by putting it behind the `spark` command? I debated doing it both ways when I created it, but thought it made for unnecessary overhead with no benefit at the time. Interested to hear your reasoning.

**Comment by jim-parry** [comment]
Are you referring to a "Laravel spark" (scaffolding?), or the "spark" microframework, or the long-gone Ci "spark"? I could be out of it, but I don't recall this coming up recently in a CI context.

**Comment by natanfelles** [comment]
I could refer to "Symfony Console spark", but no. Just a PR, yous decide.

**Comment by jim-parry** [comment]
Ok, I can't even find a reference to "Symfony console spark". It sounds like that could be another interpretation of the "verb/command". I see that this came up on the forum, and there was a lot of support for the term, which is unfortunate given the other possible interpretations. I didn't even think to refer to the forum until I remembered the thread on the CLI tool name :-/

**Pull request merged**
