### PR TITLE
Firebird support

### PR DESCRIPTION
**Pull request by turtuga**
Database driver for ibase/firebird

what works

```
select
insert
update
delete
prepared statements
create blob from file
insert blog in database
```

### Create blob

```
$ficheiro = file_get_contents($_FILES['ficheiro']['tmp_name']);

$dados = $db->create_blob($ficheiro);

$db->query("INSERT INTO FICHEIROS (FICHEIRO, NOME) VALUES (?, ?)", [$dados, $_FILES['ficheiro']['name']]);
```

### Result array
`$db->query("SELECT * FROM FICHEIROS")->getResultArray();`

### Get Row
`$db->query("SELECT * FROM FICHEIROS")->getRow();`

### Commit
`$db->commit();`

I will try keep this updated

ps. I created a new pull request because i create a new brach with this

### CODE REVIEW

**Comment by jim-parry** [comment]
1) You have version & getVersion methods. It looks to me like only the latter is in the ConnectionInterface??
2) You have a method not in the interface ... create_blob ... does the user guide need to be updated for this?
3) You have some transaction processing methods. afaik we have not addressed transactions in the core database classes. If that is the case, your methods might be premature.
4) The travis-ci build needs to be updated so unit testing is run against Firebird
5) New drivers need to be mentioned in the changelog ... not sure if this is up to the contributor or the codebase maintainer ... @lonnieezell ?

-----------
Branching is a better practice :)
Even better would be secure signing :))
See the "contributing" section in the user guide.

**Comment by lonnieezell** [comment]
I'll have to review in more detail later, but a few quick notes: 

1) Remove all transaction-related code for now. They have not been implemented yet and it's possible that they will be implemented differently than currently. Or we may add it back in like it, unsure yet. :(

2) I don't think Travis supports firebird, and am currently unsure how we can provide good tests for unsupported db systems. The two options that I can think of are to 1) build our own virtual machine that has all of the various db systems already installed that we can at least test against manually, or 2) Do some pretty intensive scripting with environments in Travis to install and build each db engine manually. I'm open to suggestions. 

3) Are you running tests against the live database while developing this to ensure the builder is working as expected, etc? There's a fairly thorough suite of tests in place for them that both MySQL and PostgreSQL are currently passing.

**Comment by turtuga** [comment]
travis show this error Error: Call to undefined function CodeIgniter\Database\Ibase\ibase_connect() 
How install php firebird extension on travis??

**Comment by jim-parry** [comment]
Carryovers from CI3-style?

- property _ibase_trans
- method affected_rows @388 vs affectedRows @216?
- method _list_tables @ 403 vs _listTables @290??
- method _list_columns @ 418 vs _listColumns @302??

**Comment by narfbg** [comment]
Prefixing with `@` notifies people with those usernames ...

**Comment by jim-parry** [comment]
Doh! thank you for the tip. That was not my intent!

**Comment by sv3tli0** [comment]
@jim-parry - CI is validating repo **lonnieezell**/CodeIgniter4.

**Pull request closed without merging**
