### PR TITLE
Use separated test configs for redis & memcached

### PR DESCRIPTION
**Pull request by puschie286**
use separated configs for testing

### CODE REVIEW

**Comment by lambasoft** [comment]
But why ?

**Comment by puschie286** [comment]
for example : i use docker for testing and docker services have a different host, redis-server has redis as host and memcached-server has memcached as host
i guess its good for every test system.

was also thinking about create a TestCache config remove the test configs from the live config

**Comment by lambasoft** [comment]
I think the Config file should stay as simple as possible, we don't want extra not so useful variables.

Maybe you can make the config variable arrays instead, something like:
```
$active_group = 'default';

$redis['default'] = array(
		'host'     => '127.0.0.1',
		'password' => null,
		'port'     => 6379,
		'timeout'  => 0,
);
```

**Comment by jim-parry** [comment]
Testing configurations can go underneath tests/ ... see tests/_support/Config, or alternately inside tests/system/Config/fixtures. There is no need to add these to application/Config

**Pull request closed without merging**
