### PR TITLE
Split validation rules

### PR DESCRIPTION
**Pull request by ytetsuro**
I felt that the number of rows of `\CodeIgniter\Validation\Rules::class` was too long.
Therefore, I divided `\CodeIgniter\Validation\Rules::class` with appropriate granularity.

### CODE REVIEW

**Comment by lonnieezell** [comment]
I can understand why you'd want this, and appreciate the effort. However, I don't think it's the best choice in this situation. By splitting it into multiple files we decrease the performance because of the increased number of files we would need to load here. Additional arrays would also be used to store the content of the files, increasing the memory footprint since arrays with string keys still aren't cheap. 

@jim-parry thoughts?

**Comment by jim-parry** [comment]
Too many lines in a class is a bad smell, agreed. Refactoring would suggest splitting the class, perhaps as you have done.
However, performance considerations and lower coupling desing patterns would suggest that your granularity is too fine, and classes should be consolidated.
Bottom line: I side with Lonnie.

@lonnieezell  One refactoring that might make sense ... splitting Rules into Rules and FormatRules (about a 50/50 split), to make the code easier to understand and/or maintain. What do you think of this?

**Comment by lonnieezell** [comment]
@jim-parry I'm cool with that type of a split. Are you able to tackle that? Or @ytetsuro can you?

**Comment by ytetsuro** [comment]
@jim-parry @lonnieezell 

> @lonnieezell One refactoring that might make sense ... splitting Rules into Rules and FormatRules (about a 50/50 split), to make the code easier to understand and/or maintain. What do you think of this?

> can you?

I can do it.
Please let me do it.
Thank you for considering.

**Comment by ytetsuro** [comment]
> splitting Rules into Rules and FormatRules (about a 50/50 split)

I pushed the fix.
It was split roughly in half.

```shell
/CodeIgniter4/ 18:41:31  (split-validation-rules)
$ cat system/Validation/Rules.php | wc -l
     363
/CodeIgniter4/ 18:41:39  (split-validation-rules)
$ cat system/Validation/FormatRules.php | wc -l
     356
```

**Comment by ytetsuro** [comment]
Merged Thanks!

**Pull request merged**
