### PR TITLE
Form helper setup.

### PR DESCRIPTION
**Pull request by Portaflex**
Have done some "dirty" work. New form_helper, new FormValidation class, and some anciliary files. The tests pass but three new functions in form_helper are not ready. Also FormValidation object is not ready. So, this is only a start point. Thanks.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Let's keep this to just the form helper for now. For starters because they're completely separate parts, and second, because I'm not sure what I want to do with Form Validation just yet, though I know there will be changes from CI3's....

**Comment by mixinix** [comment]
Old taste? Or something new?

**Comment by lonnieezell** [comment]
@Portaflex were you going to be able to remove the form validation stuff from this?

**Comment by Portaflex** [comment]
Delete this PR. Open another one without Form Validation. Thanks.

**Pull request closed without merging**
