### PR TITLE
Minor Formatting fixes & removed hardcode of forward slash instead of directory separator constant

### PR DESCRIPTION
**Pull request by ied3vil**

### CODE REVIEW

**Comment by jim-parry** [comment]
Being picky, but we expect commits to be GPG-signed :)
You might want to squash your commits - three commits to change a single line of code?

**Comment by ied3vil** [comment]
Hello
My bad there, i did it in a lunch break at work - will redo the PR this weekend if i find time, properly --

Also if you're ok i can do PRs with whatever i find that could use improvement... big fan of CI2, got a HUGE old legacy project in it that still works and i am happy to see CI4...

**Comment by jim-parry** [comment]
That would be cool, thanks

**Comment by ied3vil** [comment]
Also... why did you not make CI a package? Or is that a plan? I have not read anything just glanced the code.

**Comment by jim-parry** [comment]
A package? As in something composer-installable? There is a composer package built for it.

**Comment by samsonasik** [comment]
what @ied3vil meant probably make current `system/` as independent package so mark this as "skeleton", so in the current skeleton composer.json, there will be something like e.g.: `"codeigniter/system": "^4.0" so when there is update, user can run composer update under the skeleton.

**Comment by ied3vil** [comment]
See how laravel does it... you require the package, it includes your boilerplate and you just version it yourself, you don't need to fork the repo or something to make a new project.... just use composer require and that's it you got your working boilerplate hello world app... i understand this is not ready 4.0 yet, however i'd like it to be set up nicely... had some good times with CI... year long projects still going...

**Comment by jim-parry** [comment]
We have talked extensively about composer, and made the conscious decision that it would be supported but not required for installing CI4. Dealing with boilerplate apps is a separate issue, and we don't have any conclusions about that.

**Comment by ied3vil** [comment]
Boilerplate = minimum install of CI in my phrase above
Who does not want composer should clone the github repo. however 99% will want to use composer, why would you want to go back a few steps like that???

**Comment by jim-parry** [comment]
This "discussion" should continue on the forum - it has nothing to do with formatting ...

**Pull request merged**
