### PR TITLE
Feature/sodium

### PR DESCRIPTION
**Pull request by jim-parry**
Encryption: SodiumHandler and improvements to the OpenSSLHandler

### CODE REVIEW

**Comment by Paradinight** [comment]
What about php 7.2?
https://wiki.php.net/rfc/libsodium

https://github.com/jedisct1/libsodium-php
and
https://github.com/paragonie/sodium_compat

both added the php 7.2 function version

**Comment by jim-parry** [comment]
@Paradinight I already asked Lonnie, and we need to stick with 7.0. That means we need to remind developers to install & enable libsodium if they need it.

**Comment by jim-parry** [comment]
@lonnieezell The CI breaks because Sodium is not installed. How can I get that into the travis-ci config?

**Comment by lonnieezell** [comment]
@jim-parry Good question :) This looks like it has the info needed: https://stackoverflow.com/questions/31549471/whats-the-best-way-to-install-a-pecl-extension-libsodium-for-unit-testing-wit

**Comment by jim-parry** [comment]
Uncle ... I will come back to this later, once my head stops hurting where I have been beating it against the wall.

**Comment by Paradinight** [comment]
@jim-parry 
https://github.com/jedisct1/libsodium-php/blob/master/.travis.yml

**Comment by jim-parry** [comment]
@Paradinight I tried that already :-/ Not sure if I am getting closer or not.
I am trying to avoid sodium_compat, as I am reluctant to introduce another composer dependency.

**Comment by jim-parry** [comment]
Dropping libsodium from Travis-CI. I will rework the docs to reference external implementation. Grrr.

**Comment by jim-parry** [comment]
@lonnieezell Simplified encryption ready, with Sodium handler. Royal pain addressing libsodium and then multiple PHP versions, but done, even if the commit history is ridiculous.

**Comment by jim-parry** [comment]
Merged this so it doesnt get lost. The encryption package is much simplified (not pretending to be as flexible as CI3's) and should keep everyone happy.

**Comment by jim-parry** [comment]
@lonnieezell It looks to me like your Aug 2nd push, replacing line 499 of tests/system/Database/Live/ModelTest is breaking the travis-ci build for this PR (and possibly the SQLlite4 driver PR 646). Am I missing some travis-ci configuration thing?

**Comment by lonnieezell** [comment]
@jim-parry It's all good. I restarted the build on Travis and everything is passing now.

**Comment by jim-parry** [comment]
@lonnieezell  Thanks :) Now to figure get libsodium enabled in travis-ci!
Is it worth merging this in its current state? the unit tests pass locally with libsodium installed.

@narfbg Is this suitably simple & useful in its revised form?

**Comment by narfbg** [comment]
Not really ...

I haven't reviewed the Libsodium part, but that's not really the problem.

While defaulting to CTR and using `hash_equalis()` during authentication are improvements, the code is error-prone, all of the other [issues](https://github.com/bcit-ci/CodeIgniter4/pull/611#issuecomment-316681659) I mentioned are still present in the OpenSSL handler.
Plus, the code is quite error prone - `strcmp()` against version number strings is bad; deriving HMAC sizes out of `substr(<digestName>`, 3)` is bad too, etc. 

I thought you agreed to replace `CI_Encryption` with Libsodium, not just add another wrapper.

**Comment by jim-parry** [comment]
Fair enough - I will drop the Encryption package, and add a "recommended addins" page somewhere in the user guide (for this & other addins) directing developers to defuse/php-encryption.
We can revisit encryption, if needed, once CI4 has a minimum PHP version requirement which guarantees the availability of libsodium.

**Pull request closed without merging**
