### PR TITLE
add TestGetHeaderLine Functions.

### PR DESCRIPTION
**Pull request by xiehappy**

### CODE REVIEW

**Comment by jim-parry** [comment]
Your new method names are close, except that you are testing setHeader(), not getHeader ... oops

**Comment by xiehappy** [comment]
Sorry, I wondering why I get this error.

**Comment by jim-parry** [comment]
"This error" ... the coverage/coveralls error? It appears that that tool has determined that the code coverage has decreased. If so, that would be odd IMHO, as tests have been added.

**Comment by xiehappy** [comment]
oh, haha.. I mean "This problem". I will run the unit test locally, and double check it. Make sure there is do not have any error. Thanks, Jim

**Pull request merged**
