### PR TITLE
Remove deprecated pieces

### PR DESCRIPTION
**Pull request by jim-parry**
From the code and/or docs:
- remove filesystem_helper's read_file()
- remove url_helper's url_title separator keyword
- remove Forge::addColumn()'s 'after' parameter

### CODE REVIEW

**Comment by jim-parry** [comment]
@lonnieezell Are you ok with removing these deprecated bits? It was brought up on the forum as a confusing point. 
If we don't remove them, as was planned with 3.2(?), then we need to clarify the user guide.

**Comment by lonnieezell** [comment]
The only one I have a question about is Forge::addColumn's `after`. Any idea the reason it was deprecated? I find it handy to be able to add columns in a certain location when I'm modifying a schema. 

If we do end up removing it, does simply removing that parameter take care of the whole issue?

**Comment by jim-parry** [comment]
"After" can be specifeid as one of the preferences, rather than needing to be a separate parameter altogether. This change was planned as part of CI3.2, if I read the code correctly.
https://bcit-ci.github.io/CodeIgniter4/database/forge.html#adding-a-column-to-a-table

The docs suggest that "after" is supported by mysql & cubird (?), implying that it isn't supported by the others.

**Comment by jim-parry** [comment]
ps - I see that coveralls thinks that the coverage has decreased. I get different (higher) code coverage results when I run the unit tests locally.

**Comment by lonnieezell** [comment]
Ah, gotcha. That makes sense. Then I'm cool with them all being removed. 

And, yeah, coveralls does some weird things sometimes.

**Pull request merged**
