### PR TITLE
Text helper documentation

### PR DESCRIPTION
**Pull request by Portaflex**
Documentation for text helper, merging string and text helpers documentation. Excerpt added at the end of the chapter.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Looks pretty good. Need help getting code signing up and running?

**Comment by Portaflex** [comment]
Thanks a lot. Yes I'm stuck with code signing and need help. I use Eclipse Neon.

**Comment by Portaflex** [comment]
I think the pull request is signed, but travis-ci ...

**Comment by lonnieezell** [comment]
Yay! You got the PR signing working. :) 

> I think the pull request is signed, but travis-ci ...

You're right there's an error. If you click on the "Details" link, it will take you to the page, where you can see two different runs - the top one for MySQL and the bottom one for PostgreSQL. Click on the numbers there and you'll see the results. Though you should probably install PHPUnit locally and run the tests there first...

In this case, one of the type-hints on a text-helper method is causing an issue. Not sure if the issue is with the test or the restriction of the type hint, though I'd guess it's the test needs to be modified, since typically restricting to a certain type is a good thing.

**Comment by lonnieezell** [comment]
Do you have phpunit installed locally? That's usually easier than doing a bunch of commits to let Travis run them (and is easier on Travis, too).

**Comment by Portaflex** [comment]
Finally got it !!!
I had to add another pull request to application/Config/ForeignCharacters.php
Thanks.

**Comment by jim-parry** [comment]
@Portaflex You got one commit signed, Aug 7th, but not the others? The intent is that all of the commits be signed, so that we can prove the provenance of contributed code, thanks!

**Pull request closed without merging**
