### PR TITLE
Move Debug Toolbar to Page Bottom

### PR DESCRIPTION
**Pull request by natanfelles**

### CODE REVIEW

**Comment by EpicKris** [comment]
Shouldn't this be a configuration option?

**Comment by timothymarois** [comment]
I agree it should be an option, by default I would assume bottom like most dev tools.

**Comment by EpicKris** [comment]
The way I thought the configurable option would work was to just set an additional class `debug-bar-fixed-top` or `debug-bar-fixed-bottom` depending on the configuration option and adjusting the CSS for either class.

**Comment by lonnieezell** [comment]
@EpicKris For some reason I wasn't even thinking of a config option in a manual config file. I was thinking the user would want to adjust while there on the page. A config option is definitely simpler, though I think the usability might be a little better if you could do it live. I'm cool with a config option, though.

**Comment by EpicKris** [comment]
@lonnieezell The way you said makes far more sense than I what I was thinking, but you could still take the same route using classes with relatively minimal extra Javascript.

**Comment by natanfelles** [comment]
OK. Now the debug bar (and the icon) is being placed in the bottom by default.

I added a "button" to make the position optional by creating a cookie to control whether it should stay at the bottom or top.

Please test and give your opinion.

captura de tela de 2017-07-27 21-09-00
captura de tela de 2017-07-27 21-08-46
captura de tela de 2017-07-27 21-08-30
captura de tela de 2017-07-27 21-08-10

**Comment by lonnieezell** [comment]
I think that's great. Nice and simple and appears to work quite well. Thanks! Merging.

**Pull request merged**
