### PR TITLE
Updated Validation Process Rules Method

### PR DESCRIPTION
**Pull request by EpicKris**
No longer fails if there are no rules.

Signed-off-by: Kristian Matthews <kristian.matthews@me.com>

### CODE REVIEW

**Comment by lonnieezell** [comment]
I dunno. I'm torn on this one. I think a better solution might just be to fail louder and throw an exception if there's no rules specified. That way the developer knows he missed a series of validations that could lead to a potential security issue, and fix it before it makes it to production. 

Can you think of any times where it would be helpful NOT to have any rules? Seems like it would only happen when the developer got distracted and left the rules out, or similar.

**Comment by EpicKris** [comment]
With my model validation, I include all the fields from the relevant table regardless of if there are any rules for it or not, it may be an entirely optional field with no validation associated with it.

**Comment by EpicKris** [comment]
Perhaps a solution would be to have an `allowEmptyRules` configuration?

**Comment by lonnieezell** [comment]
Sorry, I'm not convinced. I think it's better in the core to fail loudly here. In your specific instance you could easily do an array_filter prior to handing the rules, if you've decided you want to allow that.

**Comment by EpicKris** [comment]
What about an `optional` validation rule in its place? This way the rule has to be specifically set.

**Comment by lonnieezell** [comment]
I think that adds unnecessary complexity. I'm not sure I understand where the problem is, honestly. If you don't have any rules to validate for that column, don't add it to the validation array. If your custom model has business needs that require it to have empty rules, strip them out before calling validate().

**Pull request closed without merging**
