### PR TITLE
update installation instruction with include composer create-project

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by lonnieezell** [comment]
This makes it sound like Composer is required. It will NOT be required for a final release. If you can switch it so it's obviously an optional usage, I'm fine with this.

**Comment by samsonasik** [comment]
Do you have wording change suggestion for it?

**Comment by lonnieezell** [comment]
Well, saying it "is installed" implies it's mandatory, so a minimum change would be "can be installed". Perhaps even better, something like: 

> While not required, CodeIgniter can be installed....

**Comment by samsonasik** [comment]
ok, updated

**Pull request merged**
